#!/usr/bin/env bash

bin=`which $0`
bin=`dirname ${bin}`
bin=`cd "$bin"; pwd`

echo ""
function  print_usage() {
  echo "Usage:"
  echo "clic -command Args[...]"
  echo "where command is one of:"
  echo "     -submit_plan <planName> <planDagPath>   Submit a plan/task"
  echo "     -list_tasks                             Get a list of all tasks"
  echo "     -get_task <taskName>                    Get detailed information of a specified task"
  echo "     -get_task_stages <taskName>             Get information on all stages of a task"
  echo "     -get_stage <stageId>                    Get detailed information of a specified stage"
  echo "     -version                                Print version information"
  echo "     -help                                   Show the usage"
  echo ""
}
if [ $# = 0 ]; then
  print_usage
  exit
fi

command=$1
shift
case $command in
  --help|-help|-h)
    print_usage
    exit
    ;;
esac
#set PATH
if [ -d "$CLIC_HOME/" ]; then
  PATH=$CLIC_HOME/jars
elif [ -d "/data/jars" ]; then
  CLIC_HOME="/data"
  PATH=$CLIC_HOME/jars
else
  echo  "Error: CLIC service is not found."
fi
#get conf
if [ -f "$CLIC_HOME/conf/master-info.config" ]; then
  config="$CLIC_HOME/conf/master-info.config"
  . $config
else
   echo  "Error: CLIC config is not found."
fi

#set master ip&port
master_host="${ip}"
master_port="${port}"


#core command
if [ "$command" = "-list_tasks" ]; then
  CLASS=fdu.daslab.shellservice.ShellGetTaskList
  PATH=$PATH/"clic-shell-test.jar"
elif [ "$command" = "-version" ]; then
  CLASS=fdu.daslab.shellservice.ShellGetVersionInfo
  PATH=$PATH/"clic-shell-test.jar"
elif [ "$command" = "-submit_plan" ]; then
  CLASS=fdu.daslab.shellservice.ShellSubmitPlan
  PATH=$PATH/"clic-shell-test.jar"
else
  echo $command - invalid command
  print_usage
  exit 1
fi

#some java parameters
if [ "$JAVA_HOME" != "" ]; then
  JAVA=$JAVA_HOME/bin/java
else
  echo "Error: JAVA_HOME is not set."
  exit 1
fi
JAVA_HEAP_MAX=-Xmx1000m
eval exec "$JAVA" $JAVA_HEAP_MAX  -classpath $PATH $CLASS "$@" $master_host $master_port
